// packages/taro/vue/LuckyWheel.vue
<template>
  <view class="lucky-box" :style="{ width: boxWidth + 'px', height: boxHeight + 'px' }">
    <canvas
      type="2d"
      class="lucky-canvas"
      :id="canvasId"
      :canvasId="canvasId"
      :style="{ width: boxWidth + 'px', height: boxHeight + 'px' }"
    />
    <image
      :src="imgSrc"
      @load="myLucky.clearCanvas()"
      :style="{ width: boxWidth + 'px', height: boxHeight + 'px' }"
    ></image>
    <!-- 按钮 -->
    <view v-if="flag === 'WEB'" class="lucky-wheel-btn" @click="toPlay" :style="{ width: btnWidth + 'px', height: btnHeight + 'px' }"></view>
    <cover-view v-else class="lucky-wheel-btn" @touchstart="toPlay" :style="{ width: btnWidth + 'px', height: btnHeight + 'px' }"></cover-view>
    <!-- 图片 -->
    <view v-if="myLucky && flag !== 'WEB'">
      <view class="lucky-imgs">
        <view v-for="(block, index) in blocks" :key="index">
          <view v-if="block.imgs">
            <image v-for="(img, i) in block.imgs" :key="i" :src="img.src" @load="e => imgBindload(e, 'blocks', index, i)"></image>
          </view>
        </view>
      </view>
      <view class="lucky-imgs">
        <view v-for="(prize, index) in prizes" :key="index">
          <view v-if="prize.imgs">
            <image v-for="(img, i) in prize.imgs" :key="i" :src="img.src" @load="e => imgBindload(e, 'prizes', index, i)"></image>
          </view>
        </view>
      </view>
      <view class="lucky-imgs">
        <view v-for="(btn, index) in buttons" :key="index">
          <view v-if="btn.imgs">
            <image v-for="(img, i) in btn.imgs" :key="i" :src="img.src" @load="e => imgBindload(e, 'buttons', index, i)"></image>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import Taro from '@tarojs/taro'
import { LuckyWheel as Wheel } from 'lucky-canvas'
import { changeUnits, resolveImage, getFlag, getImage } from '../utils'
export default {
  props: {
    canvasId: {
      type: String,
      default: 'lucky-wheel'
    },
    width: {
      type: [String, Number],
      default: '600rpx'
    },
    height: {
      type: [String, Number],
      default: '600rpx'
    },
    blocks: {
      type: Array,
      default: () => []
    },
    prizes: {
      type: Array,
      default: () => []
    },
    buttons: {
      type: Array,
      default: () => []
    },
    defaultStyle: {
      type: Object,
      default: () => ({})
    },
    defaultConfig: {
      type: Object,
      default: () => ({})
    },
  },
  data () {
    return {
      flag: getFlag(),
      ctx: null,
      canvas: null,
      myLucky: null,
      boxWidth: 300,
      boxHeight: 300,
      btnWidth: 0,
      btnHeight: 0,
      imgSrc: '',
    }
  },
  watch: {
    blocks (newData) {
      this.myLucky.blocks = newData
    },
    prizes (newData) {
      this.myLucky.prizes = newData
    },
    buttons (newData) {
      this.myLucky.buttons = newData
    },
  },
  mounted () {
    console.log(this.canvasId)
    this.initLucky()
  },
  methods: {
    async imgBindload (res, name, index, i) {
      const img = this[name][index].imgs[i]
      resolveImage(img, this.canvas)
    },
    getImage () {
      const page = Taro.getCurrentInstance().page
      return getImage.call(page, this.canvasId, this.canvas)
    },
    showCanvas () {
      this.imgSrc = ''
    },
    hideCanvas () {
      if (this.flag === 'WEB') return
      this.getImage().then(res => {
        if (res.errMsg !== 'canvasToTempFilePath:ok') {
          return console.error(res)
        }
        this.imgSrc = res.tempFilePath
      })
    },
    initLucky () {
      this.boxWidth = changeUnits(this.width)
      this.boxHeight = changeUnits(this.height)
      // 某些情况下获取不到 canvas
      this.$nextTick(() => {
        setTimeout(() => {
          this.draw()
        }, 100)
      })
    },
    draw () {
      const _this = this
      const page = Taro.getCurrentInstance().page
      Taro.createSelectorQuery().in(page).select(`#${this.canvasId}`).fields({
        node: true, size: true
      }).exec((res) => {
        let flag = this.flag, rAF
        if (flag === 'WEB') {
          res[0] = {
            node: document.querySelector(`#${this.canvasId} canvas`),
            width: this.boxWidth,
            height: this.boxHeight,
          }
          // 小程序使用帧动画真机会报错
          rAF = requestAnimationFrame
        }
        if (!res[0] || !res[0].node) return console.error('lucky-canvas 获取不到 canvas 标签')
        const { node, width, height } = res[0]
        const canvas = this.canvas = node
        const ctx = this.ctx = canvas.getContext('2d')
        const dpr = this.dpr = Taro.getSystemInfoSync().pixelRatio
        canvas.width = width * dpr
        canvas.height = height * dpr
        ctx.scale(dpr, dpr)
        const myLucky = this.myLucky = new Wheel({
          flag,
          ctx,
          dpr,
          width,
          height,
          rAF,
          setTimeout,
          clearTimeout,
          setInterval,
          clearInterval,
          unitFunc: (num, unit) => changeUnits(num + unit),
          beforeCreate: function () {
            if (flag === 'WEB') return
            const Radius = Math.min(this.config.width, this.config.height) / 2
            ctx.translate(Radius, Radius)
          },
          beforeInit: function () {
            if (flag === 'WEB') return
            ctx.translate(-this.Radius, -this.Radius)
          },
          afterInit: function () {
            _this.btnWidth = this.maxBtnRadius * 2
            _this.btnHeight = this.maxBtnRadius * 2
          },
          afterStart: () => {
            this.showCanvas()
          },
        }, {
          ...this.$props,
          start: (...rest) => this.$emit('start', ...rest),
          end: (...rest) => {
            this.$emit('end', ...rest)
            this.hideCanvas()
          },
        })
      })
    },
    play (...rest) {
      this.myLucky.play(...rest)
    },
    stop (...rest) {
      this.myLucky.stop(...rest)
    },
    toPlay () {
      this.myLucky.startCallback()
    },
  }
}
</script>

<style>
@import url('../utils/index.css');
</style>

// packages/taro/react/LuckyWheel.js
import React from 'react'
import Taro from '@tarojs/taro'
import { View, Canvas, CoverView, Image } from '@tarojs/components'
import { LuckyWheel as Wheel } from 'lucky-canvas'
import { changeUnits, resolveImage, getFlag, getImage } from '../utils'
import '../utils/index.css'

export default class LuckyWheel extends React.Component {
  flag = getFlag()
  ctx = null
  canvas = null
  state = {
    imgSrc: '',
    myLucky: null,
    boxWidth: 300,
    boxHeight: 300,
    btnWidth: 0,
    btnHeight: 0,
  }

  constructor (props) {
    super(props)
  }

  componentDidMount () {
    this.initLucky()
  }

  componentDidUpdate (prevProps) {
    const { props, state } = this
    if (!state.myLucky) return
    if (props.blocks !== prevProps.blocks) {
      state.myLucky.blocks = props.blocks
    }
    if (props.prizes !== prevProps.prizes) {
      state.myLucky.prizes = props.prizes
    }
    if (props.buttons !== prevProps.buttons) {
      state.myLucky.buttons = props.buttons
    }
  }

  async imgBindload (res, name, index, i) {
    const img = this.props[name][index].imgs[i]
    resolveImage(img, this.canvas)
  }

  getImage () {
    const page = Taro.getCurrentInstance().page
    return getImage.call(page, this.props.canvasId, this.canvas)
  }

  showCanvas () {
    this.setState({ imgSrc: '' })
  }

  hideCanvas () {
    if (this.flag === 'WEB') return
    this.getImage().then(res => {
      if (res.errMsg !== 'canvasToTempFilePath:ok') {
        return console.error(res)
      }
      this.setState({
        imgSrc: res.tempFilePath
      })
    })
  }

  initLucky () {
    const { props } = this
    this.setState({
      boxWidth: changeUnits(props.width),
      boxHeight: changeUnits(props.height)
    }, () => {
      // 某些情况下获取不到 canvas
      setTimeout(() => {
        this.getConfig()
      }, 100)
    })
  }

  getConfig () {
    let flag = this.flag
    const dpr = this.dpr = Taro.getSystemInfoSync().pixelRatio
    if (flag === 'WEB') {
      // H5 环境
      const divElement = document.querySelector(`#${this.props.canvasId}`)
      this.drawLucky({
        dpr,
        flag,
        divElement,
        width: this.state.boxWidth,
        height: this.state.boxHeight,
        rAF: requestAnimationFrame,
      })
    } else {
      // 小程序环境
      const page = Taro.getCurrentInstance().page
      Taro.createSelectorQuery().in(page).select(`#${this.props.canvasId}`).fields({
        node: true, size: true
      }).exec((res) => {
        if (!res[0] || !res[0].node) return console.error('lucky-canvas 获取不到 canvas 标签')
        const { node, width, height } = res[0]
        const canvas = this.canvas = node
        const ctx = this.ctx = canvas.getContext('2d')
        canvas.width = width * dpr
        canvas.height = height * dpr
        ctx.scale(dpr, dpr)
        this.drawLucky({
          dpr,
          flag,
          ctx,
          width,
          height,
        })
      })
    }
  }

  drawLucky (config) {
    const _this = this
    const { props, flag, ctx } = this
    const myLucky = new Wheel({
      ...config,
      setTimeout,
      clearTimeout,
      setInterval,
      clearInterval,
      unitFunc: (num, unit) => changeUnits(num + unit),
      beforeCreate: function () {
        if (flag === 'WEB') return
        const Radius = Math.min(this.config.width, this.config.height) / 2
        ctx.translate(Radius, Radius)
      },
      beforeInit: function () {
        if (flag === 'WEB') return
        ctx.translate(-this.Radius, -this.Radius)
      },
      afterInit: function () {
        // 动态设置按钮大小
        _this.setState({
          btnWidth: this.maxBtnRadius * 2,
          btnHeight: this.maxBtnRadius * 2,
        })
      },
      afterStart: () => {
        this.showCanvas()
      },
    }, {
      ...props,
      start: (...rest) => {
        props.onStart && props.onStart(...rest)
      },
      end: (...rest) => {
        props.onEnd && props.onEnd(...rest)
        this.hideCanvas()
      }
    })
    this.setState({ myLucky })
  }

  play (...rest) {
    this.state.myLucky.play(...rest)
  }

  stop (...rest) {
    this.state.myLucky.stop(...rest)
  }

  toPlay () {
    this.state.myLucky.startCallback()
  }

  render () {
    const { props, state, flag } = this
    const boxSize = { width: state.boxWidth + 'px', height: state.boxHeight + 'px' }
    const btnSize = { width: state.btnWidth + 'px', height: state.btnHeight + 'px' }
    const showImage = state.myLucky && flag !== 'WEB'
    return flag === 'WEB' ? <div id={props.canvasId}></div> : (
      <View className="lucky-box" style={boxSize}>
        <Canvas type="2d" className="lucky-canvas" id={props.canvasId} canvasId={props.canvasId} style={boxSize}></Canvas>
        <Image src={state.imgSrc} onLoad={() => state.myLucky.clearCanvas()} style={boxSize}></Image>
        {/* 按钮 */}
        <View className="lucky-wheel-btn" onClick={e => this.toPlay(e)} style={btnSize}></View>
        {/* 图片 */}
        { showImage ? <View className="lucky-imgs">
          {
            props.blocks.map((block, index) => <View key={index}>
              {
                block.imgs ? <View>
                  { block.imgs.map((img, i) => <Image key={i} src={img.src} onLoad={e => this.imgBindload(e, 'blocks', index, i)}></Image>) }
                </View> : null
              }
            </View>)
          }
        </View> : null }
        { showImage ? <View className="lucky-imgs">
          {
            props.prizes.map((prize, index) => <View key={index}>
              {
                prize.imgs ? <View>
                  { prize.imgs.map((img, i) => <Image key={i} src={img.src} onLoad={e => this.imgBindload(e, 'prizes', index, i)}></Image>) }
                </View> : null
              }
            </View>)
          }
        </View> : null }
        { showImage ? <View className="lucky-imgs">
          {
            props.buttons.map((button, index) => <View key={index}>
              {
                button.imgs ? <View>
                  { button.imgs.map((img, i) => <Image key={i} src={img.src} onLoad={e => this.imgBindload(e, 'buttons', index, i)}></Image>) }
                </View> : null
              }
            </View>)
          }
        </View> : null }
      </View>
    )
  }
}

LuckyWheel.defaultProps = {
  canvasId: 'lucky-wheel',
  width: '600rpx',
  height: '600rpx',
  blocks: [],
  prizes: [],
  buttons: [],
  defaultStyle: {},
  defaultConfig: {},
}
