// src/LuckyGrid.vue
<template>
  <div ref="luckyGrid"></div>
</template>

<script>
import { LuckyGrid } from 'lucky-canvas'
import pkg from '../package.json'

const name = pkg.name
const version = pkg.version

export default {
  name:'LuckyGrid',
  props: {
    width: { type: [String, Number], default: '' },
    height: { type: [String, Number], default: '' },
    cols: { type: [String, Number], default: 3 },
    rows: { type: [String, Number], default: 3 },
    prizes: { type: Array, default: () => [] },
    buttons: { type: Array, default: () => [] },
    button: { type: Object },
    blocks: { type: Array, default: () => [] },
    defaultStyle: { type: Object, default () { return {} } },
    activeStyle: { type: Object, default () { return {} } },
    defaultConfig: { type: Object, default: () => { return {} } },
    demo: { type: Boolean, default: false },
  },
  data () {
    return {
      $lucky: null,
    }
  },
  watch: {
    cols (newData, oldData) {
      this.$lucky.cols = newData
    },
    rows (newData, oldData) {
      this.$lucky.rows = newData
    },
    blocks (newData, oldData) {
      this.$lucky.blocks = newData
    },
    prizes (newData, oldData) {
      this.$lucky.prizes = newData
    },
    buttons (newData, oldData) {
      this.$lucky.buttons = newData
    },
    button (newData, oldData) {
      this.$lucky.button = newData
    },
  },
  mounted () {
    // 添加版本信息到标签上, 方便定位版本问题
    this.$refs.luckyGrid.setAttribute('package', `${name}@${version}`)
    try {
      this.initLucky()
      this.$emit('success')
    } catch (err) {
      this.$emit('error', err)
    } finally {
      this.$emit('finally')
    }
  },
  methods: {
    initLucky () {
      this.$lucky = new LuckyGrid({
        flag: 'WEB',
        width: this.width,
        height: this.height,
        divElement: this.$refs.luckyGrid,
        rAF: window.requestAnimationFrame,
        setTimeout: window.setTimeout,
        setInterval: window.setInterval,
        clearInterval: window.clearInterval,
      }, {
        ...this.$props,
        start: (...rest) => {
          this.$emit('start', ...rest)
        },
        end: (...rest) => {
          this.$emit('end', ...rest)
        },
      })
    },
    init () {
      this.$lucky && this.$lucky.init({})
    },
    play (...rest) {
      this.$lucky.play(...rest)
    },
    stop (...rest) {
      this.$lucky.stop(...rest)
    },
  }
}
</script>

// packages/react/src/components/LuckyGrid.js
import React from 'react'
import { LuckyGrid as Grid } from 'lucky-canvas'
import { name, version } from '../../package.json'

export default class LuckyGrid extends React.Component {
  constructor (props) {
    super(props)
    this.myLucky = React.createRef()
  }
  componentDidMount () {
    const { props } = this
    this.myLucky.current.setAttribute('package', `${name}@${version}`)
    try {
      this.initLucky()
      props.onSuccess && props.onSuccess()
    } catch (err) {
      props.onError && props.onError(err)
    } finally {
      props.onFinally && props.onFinally(err)
    }
  }
  componentDidUpdate (prevProps) {
    if (!this.lucky) return
    if (this.props.width !== prevProps.width) {
      this.lucky.width = this.props.width
    }
    if (this.props.height !== prevProps.height) {
      this.lucky.height = this.props.height
    }
    if (this.props.cols !== prevProps.cols) {
      this.lucky.cols = this.props.cols
    }
    if (this.props.rows !== prevProps.rows) {
      this.lucky.rows = this.props.rows
    }
    if (this.props.blocks !== prevProps.blocks) {
      this.lucky.blocks = this.props.blocks
    }
    if (this.props.prizes !== prevProps.prizes) {
      this.lucky.prizes = this.props.prizes
    }
    if (this.props.buttons !== prevProps.buttons) {
      this.lucky.buttons = this.props.buttons
    }
  }
  initLucky () {
    const { props } = this
    this.lucky = new Grid({
      flag: 'WEB',
      divElement: this.myLucky.current
    }, {
      ...props,
      start: (...rest) => {
        props.onStart && props.onStart(...rest)
      },
      end: (...rest) => {
        props.onEnd && props.onEnd(...rest)
      }
    })
  }
  init (...rest) {
    this.$lucky.init(...rest)
  }
  play (...rest) {
    this.lucky.play(...rest)
  }
  stop (...rest) {
    this.lucky.stop(...rest)
  }
  render () {
    return <div ref={this.myLucky}></div>
  }
}

LuckyGrid.defaultProps = {
  width: '',
  height: '',
  cols: 3,
  rows: 3,
  blocks: [],
  prizes: [],
  buttons: [],
  defaultStyle: {},
  activeStyle: {},
  defaultConfig: {},
}
